maximum_name: 50
maximum_email: 255
minimum_password: 6
gravatar_size: 80
gravatar_user_size: 50
password_expired: 2
content_maximum: 140
size_image: 5
resize_image: 400
type_image: "image/jpeg,image/gif,image/png"
